### ISSUE TITLE
哥们把qq号隐藏吧，我都找到你老婆了lol

### ISSUE THREAD

**Issue by anglee0323** [SirYuxuan/wife-push#1]
# **⚠️ 安全报告**

## **描述安全问题**

*

---

### **重现步骤**

1.
2.
3.
4.

---

### **预期行为**

*

---

### **媒体证据**

---

### **您的环境**

* 操作系统：
* Node 版本：
* Npm 版本：
* 浏览器名称和版本：

---

### **其他上下文**

*

**Comment by SirYuxuan** [comment]
感谢你的提示，不过readme里面的是我的qq呀
